version: '3'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${PWDDB}
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - ${PORTBD}:5432
  app:
    container_name: onboarding-api
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
volumes:
  data: null
